const { DataTypes } = require('sequelize');
const { sequelize } = require('../database/db');

const Producto = sequelize.define('Producto', {
    idProducto:{type: DataTypes.INTEGER, primaryKey: true ,autoIncrement: true},
    modificacion:{type: DataTypes.DATE , allowNull: false , defaultValue: DataTypes.NOW},
    creacion:{type: DataTypes.DATE , allowNull: false , defaultValue: DataTypes.NOW},
    idUsuario:{type: DataTypes.BIGINT, allowNull: false ,validate: {isInt:true}},
    descripcion:{type: DataTypes.STRING(600), allowNull: false ,validate: {len: [1, 500]}},
    status:{type: DataTypes.INTEGER , allowNull:false ,validate: {isInt: true}, defaultValue : 1},
    observaciones:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 900]}},
    codigoBarras:{type: DataTypes.STRING, allowNull: false ,validate: {len: [1, 20]}},
    utilidad:{type: DataTypes.INTEGER , allowNull:false ,validate: {isInt: true}, defaultValue : 1},
    ultimaVenta:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    ultimaCompra:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    costoP:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    existencia:{type: DataTypes.INTEGER , allowNull: false ,validate: {isInt:true}},
    precioP:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    unidad:{type: DataTypes.STRING, allowNull: false ,validate: {len:[1, 100]}},
    idEmpresa:{type: DataTypes.BIGINT, allowNull: false ,validate: {isInt:true}},
    incluyeFlete:{type: DataTypes.BOOLEAN , allowNull:false , defaultValue: false},
    idSucursal:{type: DataTypes.BIGINT, allowNull: false ,validate: {isInt:true}},
    idCategoria:{type: DataTypes.BIGINT, allowNull: false ,validate: {isInt:true}},
    delete:{type: DataTypes.BOOLEAN , allowNull:false , defaultValue: false},
    sKU:{type: DataTypes.STRING, allowNull: false ,validate: {len: [1, 25]}},
    skuFabricante:{type: DataTypes.STRING, allowNull: false ,validate: {len: [1, 25]}},
    upcEan:{type: DataTypes.STRING, allowNull: false ,validate: {len: [1, 25]}},
    minimoResurtido:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    largo:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    ancho:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    alto:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    numParte:{type: DataTypes.STRING, allowNull: true ,validate: {len: [1, 100]}},
    tamano:{type: DataTypes.STRING, allowNull: true ,validate: {len: [1, 100]}},
    presentacion:{type: DataTypes.STRING, allowNull: true ,validate: {len: [1, 100]}},
    unidadEntrada:{type: DataTypes.STRING, allowNull: true ,validate: {len: [1, 100]}},
    unidadSalida:{type: DataTypes.STRING, allowNull: true ,validate: {len: [1, 100]}},
    factorConversion:{type: DataTypes.STRING, allowNull: true ,validate: {len: [1, 100]}},
    ingredienteActivo:{type: DataTypes.STRING(500), allowNull: true ,validate: {len: [1, 900]}},
    esAntibiotico:{type: DataTypes.BOOLEAN , allowNull:false , defaultValue: false},
    maxStock:{type: DataTypes.DECIMAL(18,2) , allowNull:true , defaultValue: 0.00},
    minStock:{type: DataTypes.DECIMAL(18,2) , allowNull:true , defaultValue: 0.00},
    claveProducto:{type: DataTypes.BIGINT, allowNull: false ,validate: {isInt:true}},
    claveProdServ:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 30]}},
    seEdito:{type: DataTypes.BOOLEAN , allowNull:true , defaultValue: false},
    tienePrecio:{type: DataTypes.BOOLEAN , allowNull:true , defaultValue: true},
    fraccion:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 10]}},
    grupo:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 16]}},
    iVA:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    iEPS:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    precio1:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    precio2:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    precio3:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    precio4:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    precio5:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    idLote:{type: DataTypes.BIGINT, allowNull: true},
    idCedula:{type: DataTypes.BIGINT, allowNull: true},
    productoListaMostrador:{type: DataTypes.BOOLEAN , allowNull:true , defaultValue: false},
    adicional1:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 100]}},
    adicional2:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 100]}},
    adicional3:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 100]}},
    adicional4:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 100]}},
    adicional5:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 100]}},
    ordenListaPrecios:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 20]}},
    indicacion1:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion2:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion3:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion4:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion5:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion6:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion7:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion8:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion9:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    indicacion10:{type: DataTypes.STRING(600), allowNull: true ,validate: {len: [0, 200]}},
    valorEnMonedero:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 20]}},
    acomodoAlmacen:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 200]}},
    ordenAlmacen:{type: DataTypes.BIGINT, allowNull: true ,validate: {isInt:true}, defaultValue: 0},
    claveProducto2:{type: DataTypes.BIGINT, allowNull: true},
    esProvedorExterno:{type: DataTypes.BOOLEAN , allowNull:false , defaultValue: false},
    revisado:{type: DataTypes.BOOLEAN , allowNull:false , defaultValue: false},
    conteo:{type: DataTypes.INTEGER , allowNull:true },
    unidadMedida:{type: DataTypes.STRING, allowNull: true ,validate: {len: [1, 10]}},
    sincroniza:{type: DataTypes.BOOLEAN , allowNull:false , defaultValue: false},
    enviado:{type: DataTypes.BOOLEAN , allowNull:false , defaultValue: false},
    cantidadPlanApego:{type: DataTypes.INTEGER , allowNull:true},
    registroSanitario:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 300]}},
    precio6:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    precio7:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    precio8:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    precio9:{type: DataTypes.DECIMAL(19,2) , allowNull:false , defaultValue: 0.00},
    lote:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 100]}},
    fechaCaducidad:{type: DataTypes.DATE , allowNull: true},
    cuota:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    costo01:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    costo02:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    costo03:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    costo04:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    costo05:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    orderAlmacenLocal:{type: DataTypes.BIGINT, allowNull: true},
    uidProducto:{type: DataTypes.STRING, allowNull: true ,validate: {len: [20, 80]}},
    comisionProveedor:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    comisionMedico:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    productoPorComision:{type: DataTypes.BOOLEAN , allowNull:true , defaultValue: false},
    pesoProducto:{type: DataTypes.DECIMAL(19,2) , allowNull:true , defaultValue: 0.00},
    unidadPeso:{type: DataTypes.STRING, allowNull: true ,validate: {len: [0, 8]}},
});

module.exports = Producto;